### ISSUE TITLE
Unable to set jvm options

### ISSUE THREAD

**Issue by rich-murray** [realityforge/chef-glassfish#27]
Hi, 

I'm not sure if this is an issue or my misunderstanding (I'm quite new to Chef).  
I'm trying to specify some extra jvm_options but they don't appear in the Glassfish admin console.  I am using the attribute_driven_domain recipe and have the following configured using a TestKitchen kitchen.yml file.  

```YAML
---
driver:
  name: vagrant
  network: 
  - ["forwarded_port", {guest: 4849, host: 1234}]
  - ["forwarded_port", {guest: 7070, host: 8090}]
  customize:
    memory: 1024

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver_config:
      box: precise64
      box_url: http://files.vagrantup.com/precise64.box
suites:
  - name: default
    run_list:
      - recipe[bpm_test_server::default]
    attributes:
      java:
        install_flavor: oracle
        jdk_version: "7"         
        oracle:
          accept_oracle_download_terms: true       
      glassfish:       
        version: '3.1.2.2'
        base_dir: /opt/glassfish3
        domains_dir: /opt/glassfish3/glassfish/domains
        domains:
          LIVE:
            config:
              min_memory: 1024
              max_memory: 1024
              max_perm_size: 256
              port: 7070
              admin_port: 4849
              username: 'adminuser'
              password: 'adminpw'
              remote_access: true
              secure: false
              jvm_options:
              - '-Duk.co.mycompany.testprop=foobar'
              - '-Dmytest=value' 
```

The recipe in the run_list above just contains the following:
```ruby
include_recipe 'glassfish::default'
include_recipe 'glassfish::attribute_driven_domain'
```

Glassfish 3 installs OK and my domain is created but I don't see the jvm_options in the admin console (against configurations -> server-config -> jvm settings -> jvm options)

What I'm trying to achieve is to add jvm options the way you would run
asadmin create-jvm-options --target server-config -Dsomething=value

Is this possible using the attribute_driven_domain recipe?  Do I have the syntax wrong or should I be using the asadmin LWRP?  Hope you can point me in the right direction.

Thanks, 
Richard,
